controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

reports:
  path: /reports/{filename}
  controller: App\Controller\ReportsController::showSelected
